/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/compute/bias": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Compute Bias */
        post: operations["compute_bias_compute_bias_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/compute/capability": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Compute Capability */
        post: operations["compute_capability_compute_capability_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/compute/capability/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Compute Capability Analyze */
        post: operations["compute_capability_analyze_compute_capability_analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/compute/control-chart/cusum": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Compute Cusum */
        post: operations["compute_cusum_compute_control_chart_cusum_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/compute/control-chart/ewma": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Compute Ewma */
        post: operations["compute_ewma_compute_control_chart_ewma_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/compute/control-chart/i-mr": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Compute I Mr */
        post: operations["compute_i_mr_compute_control_chart_i_mr_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/compute/control-chart/xbar-r": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Compute Xbar R */
        post: operations["compute_xbar_r_compute_control_chart_xbar_r_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/compute/control-chart/xbar-s": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Compute Xbar S */
        post: operations["compute_xbar_s_compute_control_chart_xbar_s_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/compute/descriptive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Compute Descriptive */
        post: operations["compute_descriptive_compute_descriptive_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/compute/gage-rr": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Compute Gage Rr */
        post: operations["compute_gage_rr_compute_gage_rr_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/compute/linearity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Compute Linearity */
        post: operations["compute_linearity_compute_linearity_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/compute/rules/nelson": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Compute Nelson Rules */
        post: operations["compute_nelson_rules_compute_rules_nelson_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/compute/rules/western-electric": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Compute Western Electric Rules */
        post: operations["compute_western_electric_rules_compute_rules_western_electric_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/compute/stability": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Compute Stability */
        post: operations["compute_stability_compute_stability_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ingest File */
        post: operations["ingest_file_ingest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rules/catalogue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Rules Catalogue
         * @description The human-readable rule descriptions, keyed by rule number.
         */
        get: operations["rules_catalogue_rules_catalogue_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnalyzeCapabilityRequest */
        AnalyzeCapabilityRequest: {
            /**
             * Alpha
             * @default 0.05
             */
            alpha: number;
            /** Data */
            data: number[];
            /** Lsl */
            lsl?: number | null;
            /** Target */
            target?: number | null;
            /** Usl */
            usl?: number | null;
        };
        /** BiasReportOut */
        BiasReportOut: {
            /** Alpha */
            alpha: number;
            /** Bias */
            bias: number;
            /** Bias Significant */
            bias_significant: boolean;
            /** Ci Lower */
            ci_lower: number;
            /** Ci Upper */
            ci_upper: number;
            /** Mean */
            mean: number;
            /** N */
            n: number;
            /** P Value */
            p_value: number | null;
            /** Reference */
            reference: number;
            /** Repeatability */
            repeatability: number;
            /** Std Error */
            std_error: number;
            /** T Statistic */
            t_statistic: number | null;
            /** Warnings */
            warnings: string[];
        };
        /**
         * BiasRequest
         * @description Repeated readings of one part whose true value is known.
         */
        BiasRequest: {
            /**
             * Alpha
             * @default 0.05
             */
            alpha: number;
            /** Measurements */
            measurements: number[];
            /** Reference */
            reference: number;
        };
        /** Body_ingest_file_ingest_post */
        Body_ingest_file_ingest_post: {
            /** File */
            file: string;
        };
        /** BoxCoxCapabilityOut */
        BoxCoxCapabilityOut: {
            capability: components["schemas"]["CapabilityReportOut"];
            /** Lmbda */
            lmbda: number;
            /** Lsl */
            lsl: number | null;
            /** Lsl Transformed */
            lsl_transformed: number | null;
            /** N */
            n: number;
            normality_after: components["schemas"]["NormalityAssessmentOut"];
            /** Target */
            target: number | null;
            /** Target Transformed */
            target_transformed: number | null;
            /** Transform Successful */
            transform_successful: boolean;
            /** Usl */
            usl: number | null;
            /** Usl Transformed */
            usl_transformed: number | null;
            /** Warnings */
            warnings: string[];
        };
        /** CapabilityAnalysisOut */
        CapabilityAnalysisOut: {
            box_cox: components["schemas"]["BoxCoxCapabilityOut"] | null;
            normal: components["schemas"]["CapabilityReportOut"] | null;
            normality: components["schemas"]["NormalityAssessmentOut"];
            /**
             * Path
             * @enum {string}
             */
            path: "normal" | "box-cox" | "percentile";
            percentile: components["schemas"]["PercentileCapabilityOut"] | null;
            /** Pp */
            pp: number | null;
            /** Ppk */
            ppk: number | null;
            /** Rationale */
            rationale: string;
            /** Warnings */
            warnings: string[];
        };
        /** CapabilityReportOut */
        CapabilityReportOut: {
            /** Cp */
            cp: number | null;
            /** Cpk */
            cpk: number | null;
            /** Cpl */
            cpl: number | null;
            /** Cpm */
            cpm: number | null;
            /** Cpu */
            cpu: number | null;
            /** Lsl */
            lsl: number | null;
            /** Mean */
            mean: number;
            /** N */
            n: number;
            normality: components["schemas"]["NormalityAssessmentOut"] | null;
            /** Pp */
            pp: number | null;
            /** Ppk */
            ppk: number | null;
            /** Ppl */
            ppl: number | null;
            /** Ppu */
            ppu: number | null;
            /** Sigma Overall */
            sigma_overall: number;
            /** Sigma Within */
            sigma_within: number;
            /** Stability Ratio */
            stability_ratio: number | null;
            /** Subgroup Size */
            subgroup_size: number;
            /** Subgroups */
            subgroups: number;
            /** Target */
            target: number | null;
            /** Usl */
            usl: number | null;
            /** Warnings */
            warnings: string[];
            /**
             * Within Method
             * @enum {string}
             */
            within_method: "pooled" | "rbar_d2" | "sbar_c4" | "moving_range";
        };
        /** CapabilityRequest */
        CapabilityRequest: {
            /**
             * Alpha
             * @default 0.05
             */
            alpha: number;
            /** Data */
            data: number[] | number[][];
            /** Lsl */
            lsl?: number | null;
            /** Target */
            target?: number | null;
            /** Usl */
            usl?: number | null;
            /** Within Method */
            within_method?: ("pooled" | "rbar_d2" | "sbar_c4" | "moving_range") | null;
        };
        /** ChartPairOut */
        ChartPairOut: {
            dispersion: components["schemas"]["ControlChartOut"];
            /** In Control */
            in_control: boolean;
            location: components["schemas"]["ControlChartOut"];
            /** Sigma Within */
            sigma_within: number;
            /** Subgroup Size */
            subgroup_size: number;
            /** Subgroups */
            subgroups: number;
            /** Warnings */
            warnings: string[];
        };
        /** ControlChartOut */
        ControlChartOut: {
            /** In Control */
            in_control: boolean;
            limits: components["schemas"]["ControlLimitsOut"];
            /** Name */
            name: string;
            /** Points */
            points: number[];
            /** Violations */
            violations: number[];
        };
        /** ControlLimitsIn */
        ControlLimitsIn: {
            /** Center */
            center: number;
            /** Lower */
            lower: number;
            /** Upper */
            upper: number;
        };
        /** ControlLimitsOut */
        ControlLimitsOut: {
            /** Center */
            center: number;
            /** Lower */
            lower: number;
            /** Upper */
            upper: number;
        };
        /** CusumChartOut */
        CusumChartOut: {
            /** H */
            H: number;
            /** K */
            K: number;
            /** H */
            h: number;
            /** In Control */
            in_control: boolean;
            /** K */
            k: number;
            /** Lower */
            lower: number[];
            /** Sigma */
            sigma: number;
            /** Target */
            target: number;
            /** Upper */
            upper: number[];
            /** Violations */
            violations: number[];
            /** Warnings */
            warnings: string[];
        };
        /** CusumRequest */
        CusumRequest: {
            /** Data */
            data: number[];
            /**
             * H
             * @default 5
             */
            h: number;
            /**
             * K
             * @default 0.5
             */
            k: number;
            /** Sigma */
            sigma?: number | null;
            /** Target */
            target?: number | null;
        };
        /** DescriptiveRequest */
        DescriptiveRequest: {
            /** Data */
            data: number[];
        };
        /** DescriptiveSummaryOut */
        DescriptiveSummaryOut: {
            /** Iqr */
            iqr: number;
            /** Kurtosis */
            kurtosis: number | null;
            /** Lag1 Autocorrelation */
            lag1_autocorrelation: number | null;
            /** Maximum */
            maximum: number;
            /** Mean */
            mean: number;
            /** Median */
            median: number;
            /** Minimum */
            minimum: number;
            /** N */
            n: number;
            /** Q1 */
            q1: number;
            /** Q3 */
            q3: number;
            /** Range */
            range: number;
            /** Skewness */
            skewness: number | null;
            /** Std Dev */
            std_dev: number;
            /** Variance */
            variance: number;
        };
        /** EwmaChartOut */
        EwmaChartOut: {
            /** L */
            L: number;
            /** In Control */
            in_control: boolean;
            /** Lmbda */
            lmbda: number;
            /** Lower */
            lower: number[];
            /** Points */
            points: number[];
            /** Sigma */
            sigma: number;
            /** Steady State Limits */
            steady_state_limits: [
                number,
                number
            ];
            /** Target */
            target: number;
            /** Upper */
            upper: number[];
            /** Violations */
            violations: number[];
            /** Warnings */
            warnings: string[];
        };
        /** EwmaRequest */
        EwmaRequest: {
            /**
             * L
             * @default 3
             */
            L: number;
            /** Data */
            data: number[];
            /**
             * Lmbda
             * @default 0.2
             */
            lmbda: number;
            /** Sigma */
            sigma?: number | null;
            /** Target */
            target?: number | null;
            /**
             * Time Varying Limits
             * @default true
             */
            time_varying_limits: boolean;
        };
        /** GageRRReportOut */
        GageRRReportOut: {
            /** Interaction Included */
            interaction_included: boolean;
            /** Interaction Pvalue */
            interaction_pvalue: number | null;
            /**
             * Method
             * @enum {string}
             */
            method: "anova" | "average_range";
            /** N Operators */
            n_operators: number;
            /** N Parts */
            n_parts: number;
            /** N Trials */
            n_trials: number;
            /** Ndc */
            ndc: number | null;
            /** Pct Contribution Gage Rr */
            pct_contribution_gage_rr: number | null;
            /** Pct Contribution Part */
            pct_contribution_part: number | null;
            /** Pct Contribution Repeatability */
            pct_contribution_repeatability: number | null;
            /** Pct Contribution Reproducibility */
            pct_contribution_reproducibility: number | null;
            /** Pct Study Var Gage Rr */
            pct_study_var_gage_rr: number | null;
            /** Pct Study Var Part */
            pct_study_var_part: number | null;
            /** Pct Study Var Repeatability */
            pct_study_var_repeatability: number | null;
            /** Pct Study Var Reproducibility */
            pct_study_var_reproducibility: number | null;
            /** Pct Tolerance Gage Rr */
            pct_tolerance_gage_rr: number | null;
            /** Study Var Multiplier */
            study_var_multiplier: number;
            /** Tolerance */
            tolerance: number | null;
            /** Var Gage Rr */
            var_gage_rr: number;
            /** Var Interaction */
            var_interaction: number;
            /** Var Operator */
            var_operator: number;
            /** Var Part */
            var_part: number;
            /** Var Repeatability */
            var_repeatability: number;
            /** Var Reproducibility */
            var_reproducibility: number;
            /** Var Total */
            var_total: number;
            /** Warnings */
            warnings: string[];
        };
        /**
         * GageRRRequest
         * @description A balanced Gage R&R layout: parts x operators x trials.
         *
         *     Each innermost list is the trials for one part-operator cell. The core
         *     validates the shape (>= 2 of each) and balance and raises ValueError, mapped
         *     to 422. ``interaction_alpha`` is ignored by the average-and-range method.
         */
        GageRRRequest: {
            /** Data */
            data: number[][][];
            /**
             * Interaction Alpha
             * @default 0.25
             */
            interaction_alpha: number;
            /**
             * Method
             * @default anova
             * @enum {string}
             */
            method: "anova" | "average_range";
            /**
             * Study Var Multiplier
             * @default 6
             */
            study_var_multiplier: number;
            /** Tolerance */
            tolerance?: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IMRRequest */
        IMRRequest: {
            /** Data */
            data: number[];
        };
        /** IngestColumn */
        IngestColumn: {
            /** Dropped Missing */
            dropped_missing: number;
            /** Name */
            name: string;
            /** Values */
            values: number[];
        };
        /** IngestResponse */
        IngestResponse: {
            /** Columns */
            columns: components["schemas"]["IngestColumn"][];
            /** Ignored Columns */
            ignored_columns: string[];
            /** N Rows */
            n_rows: number;
            /** Warnings */
            warnings: string[];
        };
        /** LinearityReportOut */
        LinearityReportOut: {
            /** Alpha */
            alpha: number;
            /** Intercept */
            intercept: number;
            /** Linearity */
            linearity: number | null;
            /** Linearity Significant */
            linearity_significant: boolean;
            /** N */
            n: number;
            /** N Parts */
            n_parts: number;
            /** Part Mean Biases */
            part_mean_biases: number[];
            /** Percent Linearity */
            percent_linearity: number;
            /** Process Variation */
            process_variation: number | null;
            /** R Squared */
            r_squared: number | null;
            /** References */
            references: number[];
            /** Slope */
            slope: number;
            /** Slope P Value */
            slope_p_value: number | null;
            /** Slope Std Error */
            slope_std_error: number;
            /** Slope T Statistic */
            slope_t_statistic: number | null;
            /** Warnings */
            warnings: string[];
        };
        /**
         * LinearityRequest
         * @description Readings of several masters spanning the range, one list per master.
         */
        LinearityRequest: {
            /**
             * Alpha
             * @default 0.05
             */
            alpha: number;
            /** Measurements */
            measurements: number[][];
            /** Process Variation */
            process_variation?: number | null;
            /** References */
            references: number[];
        };
        /** NormalityAssessmentOut */
        NormalityAssessmentOut: {
            /** Alpha */
            alpha: number;
            anderson_darling: components["schemas"]["NormalityTestResultOut"];
            /** Lag1 Autocorrelation */
            lag1_autocorrelation: number | null;
            /** N */
            n: number;
            /** Normal */
            normal: boolean;
            /** Recommendation */
            recommendation: string;
            shapiro_wilk: components["schemas"]["NormalityTestResultOut"];
            /** Warnings */
            warnings: string[];
        };
        /** NormalityTestResultOut */
        NormalityTestResultOut: {
            /** Alpha */
            alpha: number;
            /** N */
            n: number;
            /** Normal */
            normal: boolean;
            /** P Value */
            p_value: number;
            /** Statistic */
            statistic: number | null;
            /** Test */
            test: string;
        };
        /** PercentileCapabilityOut */
        PercentileCapabilityOut: {
            /** Distribution */
            distribution: string;
            /** Fit Score */
            fit_score: number | null;
            /** Lsl */
            lsl: number | null;
            /** N */
            n: number;
            /** P Lower */
            p_lower: number;
            /** P Median */
            p_median: number;
            /** P Upper */
            p_upper: number;
            /** Params */
            params: number[];
            /** Pp */
            pp: number | null;
            /** Ppk */
            ppk: number | null;
            /** Ppl */
            ppl: number | null;
            /** Ppu */
            ppu: number | null;
            /** Usl */
            usl: number | null;
            /** Warnings */
            warnings: string[];
        };
        /** RuleViolationOut */
        RuleViolationOut: {
            /** Description */
            description: string;
            /** Point */
            point: number;
            /** Rule */
            rule: number;
            /** Rule Set */
            rule_set: string;
            /** Window */
            window: number[];
        };
        /**
         * RulesRequest
         * @description Run run-rules against an already-computed chart.
         *
         *     The rules are a lens over a chart: they derive their sigma zones from the
         *     chart's own limits, so the client passes the plotted points and the limits
         *     rather than raw data. ``rules`` selects a subset (Nelson himself advised
         *     against enabling all eight at once); ``None`` means all rules in the set.
         */
        RulesRequest: {
            limits: components["schemas"]["ControlLimitsIn"];
            /** Points */
            points: number[];
            /** Rules */
            rules?: number[] | null;
        };
        /** StabilityReportOut */
        StabilityReportOut: {
            chart: components["schemas"]["ChartPairOut"];
            /** Stable */
            stable: boolean;
            /** Warnings */
            warnings: string[];
        };
        /**
         * StabilityRequest
         * @description Time-ordered readings of one master: 1-D individuals or 2-D subgroups.
         */
        StabilityRequest: {
            /** Measurements */
            measurements: number[] | number[][];
        };
        /** SubgroupRequest */
        SubgroupRequest: {
            /** Subgroups */
            subgroups: number[][];
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    compute_bias_compute_bias_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BiasRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BiasReportOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compute_capability_compute_capability_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CapabilityRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CapabilityReportOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compute_capability_analyze_compute_capability_analyze_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalyzeCapabilityRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CapabilityAnalysisOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compute_cusum_compute_control_chart_cusum_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CusumRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CusumChartOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compute_ewma_compute_control_chart_ewma_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EwmaRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EwmaChartOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compute_i_mr_compute_control_chart_i_mr_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IMRRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChartPairOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compute_xbar_r_compute_control_chart_xbar_r_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubgroupRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChartPairOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compute_xbar_s_compute_control_chart_xbar_s_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubgroupRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChartPairOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compute_descriptive_compute_descriptive_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DescriptiveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DescriptiveSummaryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compute_gage_rr_compute_gage_rr_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GageRRRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GageRRReportOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compute_linearity_compute_linearity_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LinearityRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LinearityReportOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compute_nelson_rules_compute_rules_nelson_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RulesRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleViolationOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compute_western_electric_rules_compute_rules_western_electric_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RulesRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleViolationOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compute_stability_compute_stability_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StabilityRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StabilityReportOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    ingest_file_ingest_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_ingest_file_ingest_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rules_catalogue_rules_catalogue_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: {
                            [key: string]: string;
                        };
                    };
                };
            };
        };
    };
}
